name: plus_router
description: Router Module for Fluter Project
version: 1.0.0-dev.3
repository: https://github.com/BugGolf/PlusRouter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
